// App-owned canonical Chinese copy and English translations.
// {0}, {1}, … preserve interpolated values verbatim. Never add session content here.
enum LocalizationCatalog {
    static let english: [String: String] = [
        "尚无事件记录": "No events yet",
        "{0} 秒前": "{0} sec ago",
        "{0} 分钟前": "{0} min ago",
        "{0} 小时前": "{0} hr ago",
        "{0} 天前": "{0} d ago",
        "%.1f 万字符": "%.1f × 10,000 characters",
        "{0} 字符": "{0} characters",
        "调用请求 · js": "Call requested · js",
        "查看或操作应用界面": "View or control the app",
        "调用请求 · exec": "Call requested · exec",
        "执行一组工具操作": "Run a group of tools",
        "命令执行": "Command execution",
        "运行终端命令": "Run a terminal command",
        "全部": "All",
        "最新在前": "Newest first",
        "上下文": "Context",
        "轨迹": "Trace",
        "协作": "Agents",
        "推理强度 {0}": "Reasoning effort: {0}",
        "在 Codex 打开任务": "Open task in Codex",
        "复制任务标识": "Copy task ID",
        "查看父任务": "View parent task",
        "概览": "Overview",
        "最近活动": "Recent activity",
        "尚无执行记录": "No execution records yet",
        "有新的本地执行记录时，会自动显示在这里。": "New local execution records will appear here automatically.",
        "查看轨迹": "View trace",
        "上下文使用率": "Context window usage",
        "采样于 ": "Sampled at ",
        "尚无采样": "No samples yet",
        "未知": "Unknown",
        "剩余约 {0} Token": "About {0} tokens remaining",
        "剩余容量未知": "Remaining capacity unknown",
        "运行时尚未提供窗口使用率。": "The runtime has not reported window usage yet.",
        "查看上下文": "View context",
        "最近的执行记录": "Recent execution records",
        "全部轨迹": "Full trace",
        "任务有新的持久化记录时，会自动显示在这里。": "New persisted task records will appear here automatically.",
        "状态来自最近的本地记录。长时间没有新记录时，需要回到原任务确认；「本轮结束」不等于任务目标已完成。": "Status comes from the latest local records. If no new records appear for a while, check the original task. “Turn ended” does not mean the task goal is complete.",
        "关注事项": "Needs attention",
        "显示已解除": "Show resolved",
        "暂未发现需要处理的事项": "Nothing needs attention right now",
        "已解除": "Resolved",
        "已确认": "Confirmed",
        "待核实": "Unconfirmed",
        "查看依据": "View evidence",
        "打开原任务": "Open original task",
        "我已看过": "Mark as seen",
        "最早在前": "Oldest first",
        "输出最大": "Largest output",
        "耗时最长": "Longest duration",
        "按时间查看执行过程，也可以筛选失败、较大输出或较长耗时。": "Follow execution over time, or filter for failures, large outputs and long calls.",
        "执行记录": "Execution records",
        "已加载 {0} 条 · 匹配 {1} 条": "Loaded: {0} · Matching: {1}",
        "失败 {0}": "Failures: {0}",
        "全部类型": "All types",
        "搜索记录": "Search records",
        "排序": "Sort",
        "记录范围与说明": "Record coverage",
        "已加载范围：{0} — {1}": "Loaded range: {0} — {1}",
        "分类数量和排序仅针对已加载记录。工具记录可能合并调用与结果；未提供耗时或体积时保持未知。": "Counts and sorting cover loaded records only. A tool record may combine its call and result. Missing durations and sizes remain unknown.",
        "调用待返回": "Awaiting tool result",
        "工具已有记录": "Tool result recorded",
        "明确失败": "Confirmed failure",
        "没有匹配记录。可以调整类型、失败筛选或搜索，再读取更早内容。": "No matching records. Adjust the type, failure filter or search, or load earlier records.",
        "轮次标识未提供": "Turn ID unavailable",
        "轮次 {0}": "Turn {0}",
        "显示更多已加载记录（{0} 条）": "Show more loaded records ({0})",
        "正在读取…": "Loading…",
        "读取更早的记录": "Load earlier records",
        "%.2f 秒": "%.2f sec",
        "输出 ": "Output: ",
        "结果待记录": "Result not yet recorded",
        "谁在一起完成这个任务": "Agents working on this task",
        "每个 Agent 有独立上下文。点击任务查看它自己的上下文内容和执行记录。": "Each agent has its own context. Select a task to inspect its context and execution records.",
        "上下文 {0} · 采样于 {1}": "Context: {0} · Sampled at {1}",
        "没有记录到直接子任务。": "No direct child tasks recorded.",
        "正在读取内容…": "Loading content…",
        "打开 Codex Session Atlas 查看相关任务和证据。": "Open Codex Session Atlas to view the task and its evidence.",
        "监控设置": "Settings",
        "Codex 数据目录": "Codex data directory",
        "只读取本机会话。关闭窗口后继续监控，退出应用后停止。": "Reads local sessions only. Monitoring continues when the window is closed and stops when the app quits.",
        "为明确失败和等待用户的事件发送系统通知": "Notify me about confirmed failures and requests for input",
        "连续失败／重复调用：{0} 次": "Repeated failures or calls: {0}",
        "重复调用观察窗口：{0} 分钟": "Repeated-call window: {0} min",
        "上下文提示阈值：{0}%": "Context alert threshold: {0}%",
        "大输出阈值：{0} KiB": "Large output threshold: {0} KiB",
        "无新事件提示：{0} 分钟": "No-new-events threshold: {0} min",
        "保存设置": "Save settings",
        "全部会话": "All sessions",
        "任务列表": "Task list",
        "选一个任务，看看它的执行过程": "Select a task to explore its execution",
        "所有本地任务仍会持续监控。": "All local tasks are still being monitored.",
        "会话 · 轨迹 · 上下文": "Sessions · Traces · Context",
        "任务": "Tasks",
        "显示系统任务": "Show system tasks",
        "已归档": "Archived",
        "返回全部任务": "Back to all tasks",
        "查看已归档任务": "View archived tasks",
        "搜索任务、项目或模型": "Search tasks, projects or models",
        "最近活跃": "Active",
        "轮次尚未结束，且近 5 分钟有执行记录；不包含等待用户的任务。": "An unfinished turn with execution records in the last 5 minutes. Tasks waiting for user input are excluded.",
        "需关注": "Attention",
        "待关注": "Needs attention",
        "全部项目": "All projects",
        "排序：{0}": "Sort: {0}",
        "按整组最新活动排序，子任务活动也会让父任务上移。尚无执行记录时使用目录时间。可在右上角筛选菜单切换。": "Sorted by the latest activity in each task group, including child tasks. Catalog time is used when no execution records exist. Change sorting in the filter menu.",
        "正在读取任务目录": "Loading task catalog",
        "没有匹配的任务": "No matching tasks",
        "调整搜索或筛选条件。": "Adjust your search or filters.",
        "展开或收起子任务": "Expand or collapse child tasks",
        "在 Codex 打开": "Open in Codex",
        "持续观测 · 本机只读": "Monitoring · Local, read-only",
        "部分数据待恢复": "Some data needs recovery",
        "更新于 {0} · v{1}": "Updated {0} · v{1}",
        "立即刷新": "Refresh now",
        "用户输入": "User input",
        "压缩后保留": "Retained after compaction",
        "本阶段新增": "Added in this phase",
        "正文不可读": "Content unreadable",
        "耗时未提供": "Duration unavailable",
        "输出体积未提供": "Output size unavailable",
        "关闭内容": "Close content",
        "来源与记录信息": "Source and record details",
        "记录位置 {0}": "Record offset: {0}",
        "复制来源位置": "Copy source location",
        "\n记录字节位置: {0}": "\nRecord byte offset: {0}",
        "正文": "Content",
        "原始记录": "Raw record",
        "本页结束": "End of page",
        "下一页": "Next page",
        "复制内容": "Copy content",
        "含活跃子任务": "Has active child tasks",
        "· {0} 个子任务": "· Subtasks: {0}",
        "该任务及筛选范围内子任务的最近活动：{0}": "Latest activity in this task and its filtered children: {0}",
        "最近活动：{0}": "Latest activity: {0}",
        "此父任务仅用于展示活跃子任务的归属关系。": "This parent task is shown to identify the owner of active child tasks.",
        "执行脚本，展开查看代码与参数。": "Script execution. Open to view the code and arguments.",
        "终端命令，展开查看命令与参数。": "Terminal command. Open to view the command and arguments.",
        "结构化内容，展开查看完整记录。": "Structured content. Open to view the full record.",
        "失败": "Failed",
        "时间顺序": "Chronological",
        "文本最长": "Longest text",
        "查看窗口使用率，追查已记录的内容及其变化。": "Inspect window usage and trace recorded content and changes.",
        "这些数字怎么看": "How to read these numbers",
        "上下文使用率：运行时报告的已用 Token ÷ 窗口容量，是最近采样时的容量使用情况。": "Context window usage: used tokens reported by the runtime divided by window capacity, at the selected sample.",
        "已记录内容的文本占比：某类可读字符数 ÷ 所选范围全部可读字符数，不是 Token 占比。": "Recorded text share: readable characters in a category divided by all readable characters in the selected range. This is not a token share.",
        "Token 消耗：多次请求的用量统计。已有输入可能重复计入，因此累计值可大于窗口容量。": "Token consumption: usage across requests. Existing input can be counted repeatedly, so cumulative usage may exceed the window capacity.",
        "历史内容尚未读完（{0}%）。阶段、采样和组成暂时只覆盖已读取部分。": "History is still loading ({0}%). Phases, samples and composition cover only the records read so far.",
        "查看最长内容": "View longest content",
        "看两次采样间新增": "View additions between samples",
        "正在读取上下文内容": "Loading context content",
        "尚未读到上下文内容": "No context content loaded yet",
        "读取本地消息和压缩记录后，这里会显示各阶段包含的内容。": "The contents of each phase will appear after local messages and compaction records are read.",
        "重新读取": "Reload",
        "已读取 {0}% 的本地记录": "Read {0}% of local records",
        "继续读取": "Continue loading",
        "选择压缩阶段": "Compaction phase",
        "{0} 个阶段 · 每次压缩开始一个新阶段": "Phases: {0} · Each compaction starts a new phase",
        "{0} · {1} 项内容": "{0} · Items: {1}",
        "当前": "Current",
        "已读末段": "Latest loaded",
        "已用": "used",
        "按本次采样，剩余 {0} Token": "At this sample, {0} tokens remain",
        "最近采样": "Latest sample",
        "已读部分的最近采样": "Latest loaded sample",
        "正在回看": "Viewing history",
        "查看到": "View through",
        "查看时刻": "Sample time",
        "最新记录（持续更新）": "Latest records (live)",
        "上一采样": "Previous sample",
        "下一采样": "Next sample",
        "回到最新": "Back to latest",
        "点击曲线可回看。使用率来自运行时采样；下方内容来自本地日志，可能含当次输出，不等于模型请求的完整输入。": "Select a point on the chart to review history. Usage comes from runtime samples. The content below comes from local logs, may include that request’s output, and is not the full model input.",
        "时间": "Time",
        "占用 %": "Usage %",
        "模型与容量": "Model and capacity",
        "所选时刻": "Selected time",
        "上下文占用曲线；也可通过查看时刻菜单或前后按钮选择采样": "Context usage chart. You can also select a sample with the time menu or previous and next buttons.",
        "相邻采样之间发生了什么": "Changes between adjacent samples",
        "占用变化": "Usage change",
        "不可直接比较": "Not comparable",
        "新增记录": "New records",
        "{0} 项": "Items: {0}",
        "新增可读文本": "New readable text",
        "模型或窗口容量不同，暂不计算 Token 差值；内容仍按两次采样之间的日志位置列出。": "The model or window capacity differs, so no token delta is calculated. Content is still listed by its log position between the samples.",
        "这些内容在两次采样之间出现，可用于追查变化；字符量不能换算为精确 Token 贡献。": "These records appeared between the samples and can help explain changes. Character counts cannot measure exact token contributions.",
        "这是本阶段的首个采样，或尚无采样；没有同阶段的前一次记录可供比较。": "This is the first sample in this phase, or no sample is available. There is no previous sample in the same phase to compare.",
        "已记录内容的文本占比": "Recorded text share",
        "{0} 项 · {1} · {2} 项正文不可读": "Items: {0} · {1} · Unreadable: {2}",
        "清除分类筛选": "Clear category filter",
        "压缩后保留 {0} 项": "Retained after compaction: {0}",
        "本阶段新增 {0} 项": "Added in this phase: {0}",
        "点击类别查看内容。占比按可读字符计算，不是 Token 占比。": "Select a category to inspect its content. Shares use readable characters, not tokens.",
        "保留内容来自压缩后记录的消息集合；加密摘要无法读取正文。": "Retained content comes from the messages recorded after compaction. Encrypted summaries cannot be read.",
        "日志没有提供压缩后的完整消息集合，只显示已知摘要与新增内容。": "The log does not include the full post-compaction message set. Only known summaries and additions are shown.",
        "覆盖范围：本地日志可见内容。未记录的系统提示、工具定义、服务端裁剪与加密正文不在可读统计中。": "Coverage: content visible in local logs. Unrecorded system prompts, tool definitions, server-side trimming and encrypted content are excluded from readable-text statistics.",
        "不可读": "Unreadable",
        "{0} 项 · {1}": "Items: {0} · {1}",
        "{0}，{1} 项，{2}，{3}": "{0}, items: {1}, {2}, {3}",
        "已选中": "Selected",
        "点击筛选": "Select to filter",
        "内容明细": "Content details",
        "{0} 项匹配": "Matching: {0}",
        "截至所选时刻": "Through selected time",
        "两次采样间新增": "Between samples",
        "搜索内容": "Search content",
        "清除筛选": "Clear filters",
        "这个范围没有匹配内容。可以清除分类、搜索，或改看截至所选时刻的全部内容。": "No matching content in this range. Clear the category or search, or view all content through the selected time.",
        "再显示 50 条": "Show 50 more",
        "Token 消耗": "Token consumption",
        "以下是任务最新用量，不随上方历史时刻切换。每次请求都可能再次计入已有输入，因此累计值可能大于窗口容量。": "These are the latest usage totals for the task, independent of the historical time selected above. Requests can count existing input again, so cumulative usage may exceed window capacity.",
        "最近一次请求": "Latest request",
        "当前轮次": "Current turn",
        "任务累计": "Task total",
        "缓存输入属于输入，推理输出属于输出，不能再次相加；消耗不是费用估算。": "Cached input is part of input; reasoning output is part of output. Do not add them again. Consumption is not a cost estimate.",
        "输入 {0}": "Input: {0}",
        "其中缓存 {0}": "Cached: {0}",
        "输出 {0}": "Output: {0}",
        "其中推理 {0}": "Reasoning: {0}",
        "需关注优先": "Attention first",
        "本轮执行失败": "This turn failed",
        "运行时记录了失败的结束状态": "The runtime recorded a failed end state",
        "打开原任务，结合失败前的调用与错误信息处理；避免在原因未明时反复重试。": "Open the original task and inspect the preceding calls and error. Avoid retrying repeatedly before the cause is clear.",
        "等待你补充信息": "Waiting for your input",
        "已记录输入请求，尚未观察到对应响应": "An input request was recorded; no corresponding response has been observed",
        "打开原任务查看问题并作答。": "Open the original task to read and answer the question.",
        "相同调用连续失败 {0} 次": "Consecutive identical call failures: {0}",
        "最近连续调用的工具、参数和返回内容相同": "Recent consecutive calls used the same tool and arguments and returned the same content",
        "核对参数、权限和依赖是否发生变化，再决定是否继续重试。": "Check whether arguments, permissions or dependencies have changed before retrying.",
        "重复读取 {0} 次": "Repeated reads: {0}",
        "短时间内相同只读调用返回了相同内容，不代表已经形成死循环": "Identical read-only calls returned the same content in a short period. This does not prove an infinite loop",
        "检查是否可以复用已有结果，或缩小下一次查询的范围。": "Consider reusing existing results or narrowing the next query.",
        "返回内容较大": "Large output",
        "本次可见输出约 {0} KiB；不等于当前上下文实际保留量": "Visible output is about {0} KiB; this is not the amount retained in the current context",
        "优先过滤、聚合或分页返回内容；在上下文页查看随后用量变化。": "Filter, aggregate or paginate output. Check subsequent usage changes on the Context page.",
        "最近观测的上下文占用偏高": "Recently observed context usage is high",
        "最近有效占用约 {0}%，采样后新增内容尚未计入": "Latest effective usage is about {0}%. Content added after the sample is not included",
        "查看大内容来源；后续输入减少重复材料，并在必要时主动整理交接摘要。": "Inspect large content sources. Reduce repeated material in later inputs and prepare a handoff summary when needed.",
        "长时间没有新事件": "No new events for a while",
        "最近 {0} 分钟未观察到新增记录，不能据此判定卡死": "No new records observed for {0} min. This alone does not mean the task is stuck",
        "查看最后操作及原任务状态；若为构建、等待或长查询，可继续观察。": "Check the last operation and the original task. Builds, waits and long queries may need more time.",
        "状态待确认": "Status unconfirmed",
        "等待用户": "Waiting for input",
        "本轮结束": "Turn ended",
        "已中断": "Interrupted",
        "最近 5 分钟没有可确认的执行记录。日志最后标记为运行中，当前是否仍运行需到原任务确认。": "No confirmed execution records in the last 5 minutes. The log last marked this task as running; check the original task to confirm its current state.",
        "输入": "Input",
        "回复": "Replies",
        "工具": "Tools",
        "修改": "Changes",
        "压缩": "Compaction",
        "轮次": "Turns",
        "计划": "Plans",
        "可见推理摘要": "Visible reasoning summaries",
        "其他": "Other",
        "数据库暂不可读": "Database temporarily unreadable",
        "数据库查询不可用（SQLite {0}）": "Database query unavailable (SQLite {0})",
        "数据库读取中断（SQLite {0}），保留上次快照": "Database read interrupted (SQLite {0}); keeping the previous snapshot",
        "未找到 Codex 会话索引，请检查数据目录": "Codex session index not found. Check the data directory",
        "会话索引缺少标识字段": "Session index has no identifier field",
        "未知项目": "Unknown project",
        "未知来源": "Unknown source",
        "未知模型": "Unknown model",
        "此版本没有分页历史，显示已采集的日志事件": "This version has no paginated history; showing collected log events",
        "源记录已变化，无法用旧位置验证该证据；请刷新轨迹": "The source record changed and its old position can no longer verify this evidence. Refresh the trace",
        "源记录已不可用": "Source record no longer available",
        "内容编码不可显示": "Content encoding cannot be displayed",
        "源记录中已找不到这项材料": "This material is no longer present in the source record",
        "\n\n—— 本页结束，可加载下一页 ——": "\n\n— End of page. Load the next page to continue —",
        "未展示内部内容": "Internal content not displayed",
        "图像内容省略": "Image content omitted",
        "本地缓存不可写：本次仅内存采集，重启后需重新初始化": "Local cache is not writable. Collecting in memory only; restarting requires initialization again",
        "会话索引读取失败，显示上次快照：{0}": "Session index read failed; showing the previous snapshot: {0}",
        "分页历史读取失败，保留上次状态并继续采集日志：{0}": "Paginated history read failed; keeping the previous state and continuing log collection: {0}",
        "源记录读取失败，保留上次观测": "Source read failed; keeping the previous observation",
        "源记录暂不可读，仍保留会话目录": "Source temporarily unreadable; keeping the session catalog",
        "上下文按需加载，新增活动仍持续监听": "Context loads on demand; new activity is still monitored",
        "无可读的本地轨迹：仅显示目录，尚未接入实时监控": "No readable local trace. Showing catalog only; live monitoring is unavailable",
        "初始化中": "Initializing",
        "{0} 个会话等待下一批增量处理": "Sessions awaiting the next incremental batch: {0}",
        "更早的上下文记录暂不可读": "Earlier context records are temporarily unreadable",
        "分页历史不可读，显示已采集事件": "Paginated history unreadable; showing collected events",
        "日志尚未初始化": "Log not initialized yet",
        "兼容模式：按日志区段读取轨迹": "Compatibility mode: reading trace by log segments",
        "较早日志暂不可读": "Earlier logs temporarily unreadable",
        "轨迹来自持久化日志；未持久化的中间状态不可见": "Trace comes from persisted logs. Intermediate states that were not persisted are unavailable",
        "无法读取源记录：{0}": "Cannot read source record: {0}",
        "执行进展": "Progress update",
        "助手回复": "Assistant reply",
        "工具调用": "Tool call",
        "文件修改": "File changes",
        "子 Agent 活动": "Child agent activity",
        "上下文压缩": "Context compaction",
        "执行计划": "Execution plan",
        "搜索网页": "Search the web",
        "查看图片": "View image",
        "扩展调用": "Extension call",
        "未识别的事件，保留源记录": "Unrecognized event; source record retained",
        "日志归属与会话索引不一致，停止读取": "Log ownership differs from the session index; reading stopped",
        "调用请求 · {0}": "Call requested · {0}",
        "轮次开始": "Turn started",
        "错误记录": "Error record",
        "源文件已更换或截断，当前记录已重新定位": "Source file was replaced or truncated; records have been relocated",
        "日志归属与会话不一致": "Log ownership differs from the session",
        "单条记录超过 32 MiB，等待可解析的记录边界": "A record exceeds 32 MiB; waiting for a parsable record boundary",
        "部分记录无法解析，已保留其余可读数据": "Some records could not be parsed; other readable data is retained",
        "规则与指令": "Rules and instructions",
        "可用技能说明": "Available skill descriptions",
        "运行环境信息": "Runtime environment",
        "Agent 回复与进展": "Agent replies and progress",
        "工具调用内容": "Tool call content",
        "工具返回": "Tool results",
        "压缩摘要": "Compaction summary",
        "图片与附件": "Images and attachments",
        "日志中可见的行为要求、项目约定、权限边界与记忆使用说明。": "Behavior requirements, project conventions, permission boundaries and memory instructions visible in the log.",
        "可用 Skill 的介绍和调用条件，不表示这些技能都已加载或执行。": "Descriptions of available skills and when to use them. This does not mean every skill was loaded or executed.",
        "工作目录、时间、运行环境和可用插件等描述信息，不是环境健康检查。": "Working directory, time, runtime environment and available plugins. This is not an environment health check.",
        "用户提出的问题、要求和补充说明。": "Questions, requests and additional information from the user.",
        "Agent 已生成的回答与执行进展，不包含工具调用参数。": "Answers and progress updates generated by the agent, excluding tool call arguments.",
        "Agent 交给工具的具体操作，例如终端命令、搜索词和文件修改内容。": "Operations sent to tools, such as terminal commands, search terms and file changes.",
        "工具返回的文件正文、检索结果、命令输出或报错；通过工具读取的 Skill 文档也在这里。": "File content, search results, command output or errors returned by tools. Skill documents read through tools also belong here.",
        "压缩后记录的摘要；加密保存的摘要只能确认存在，无法读取正文。": "Summaries recorded after compaction. An encrypted summary can be identified but its content cannot be read.",
        "本地记录中的图片或附件信息，不能据此精确计算其 Token 用量。": "Images or attachments in local records. Their exact token usage cannot be determined from this information.",
        "首次压缩前": "Before first compaction",
        "第 {0} 次压缩后": "After compaction {0}",
        "已索引 20,000 项内容；此文件的后续内容尚未纳入组成视图。": "Indexed 20,000 items. Later content in this file is not yet included in the composition view.",
        "单条记录超过可解析范围，后续组成尚未读取。": "A record exceeds the parsing limit. Later composition has not been read.",
        "日志归属不匹配，无法建立上下文组成。": "Log ownership does not match; context composition is unavailable.",
        "部分源记录无法解析，组成视图可能不完整。": "Some source records could not be parsed. The composition view may be incomplete.",
        "上下文内容暂不可读，请重试。": "Context content is temporarily unreadable. Try again.",
        "运行时未提供可读摘要；本阶段只列出此后新增的内容。": "The runtime provided no readable summary. This phase lists only content added afterward.",
        "图像内容": "Image content",
        "音频内容": "Audio content",
        "非文本内容不计入字符组成；可在原任务中查看。": "Non-text content is excluded from character counts. View it in the original task.",
        "调用 · {0}": "Call · {0}",
        "返回 · {0}": "Result · {0}",
        "压缩后保留的摘要": "Summary retained after compaction",
        "摘要由运行时加密保存，无法读取正文；不沿用压缩前的内容冒充当前记录。": "The runtime stores this summary encrypted, so its content cannot be read. Pre-compaction content is not substituted for the current record.",
        "可用技能与调用约定": "Available skills and invocation rules",
        "项目约定 · AGENTS.md": "Project conventions · AGENTS.md",
        "目录、时间与运行环境": "Directory, time and runtime environment",
        "Codex 应用使用约定": "Codex app conventions",
        "权限与执行边界": "Permissions and execution boundaries",
        "可用插件清单": "Available plugins",
        "协作模式": "Collaboration mode",
        "Agent 分工与通信规则": "Agent roles and communication rules",
        "Agent 使用限制": "Agent usage limits",
        "记忆检索与使用约定": "Memory retrieval and usage rules",
        "关联记忆": "Related memories",
        "系统指令（日志可见部分）": "System instructions (visible in logs)",
        "运行规则与开发者指令": "Runtime rules and developer instructions",
        "终端命令": "Terminal command",
        "网页检索": "Web search",
        "工具执行": "Tool execution",
        "应用界面操作": "App interaction",
        "语言": "Language",
        "跟随系统": "System default",
        "语言立即生效。会话原文、代码和工具输出保持原样。": "Changes apply immediately. Session content, code and tool output stay in their original language.",
        "文件": "File",
        "编辑": "Edit",
        "窗口": "Window",
        "帮助": "Help",
        "关于 Codex Session Atlas": "About Codex Session Atlas",
        "隐藏 Codex Session Atlas": "Hide Codex Session Atlas",
        "隐藏其他": "Hide Others",
        "全部显示": "Show All",
        "退出 Codex Session Atlas": "Quit Codex Session Atlas",
        "关闭窗口": "Close Window",
        "最小化": "Minimize",
        "缩放": "Zoom",
        "全部置于前台": "Bring All to Front",
        "撤销": "Undo",
        "重做": "Redo",
        "剪切": "Cut",
        "复制": "Copy",
        "粘贴": "Paste",
        "全选": "Select All",
        "使用手册": "User Guide",
        "查看 GitHub 项目": "View Project on GitHub",
    ]
}
